# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: aefd3b0a6e432450bfde0d2ea6941e3c0ae33cf4cc1b7ecfe99838930eb594eaa1402465cc3f0e672c4ed4baea071eaf429cdc46aea77498b9363b143b922a40

test:
  secret_key_base: 19f16ecf7447f2863ac6c8b4c8bdf982a4beff07211cf14774bd546a70c1114a45897b5018cab0a4e330ff65fbaf017730eb370bb9d21a03720e7ca5c7bb943b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
